### PR TITLE
Add Node.js support with `neon-bindings`

### PR DESCRIPTION
**Pull request by theosirian**
Add Node.js support with `neon-bindings`.

Added build and test targets on `lib/Makefile`.

This is a substitute for #17.

### CODE REVIEW

**Comment by theosirian** [comment]
@clehner same thing here as in https://github.com/spruceid/didkit/pull/52#issuecomment-774121191

**Comment by clehner** [comment]
Great. It builds and npm tests pass for me using #55 and the following patch:
```diff
diff --git a/lib/node/native/Cargo.toml b/lib/node/native/Cargo.toml
index d89428f..cf9e78b 100644
--- a/lib/node/native/Cargo.toml
+++ b/lib/node/native/Cargo.toml
@@ -19 +19 @@ ssi = { path = "../../../../ssi", default-features = false, features = ["ed25519
-didkit = { path = "../../" }
+didkit = { path = "../../", default-features = false }
```

I think this could be added to CI:
```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index ed1b1a3..5529713 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -110,4 +110,7 @@ jobs:
       run: make -C lib ../target/test/c.stamp
 
+    - name: Test Node.js package
+      run: make -C lib ../target/test/node.stamp
+
     - name: Test JNI
       run: make -C lib ../target/test/java.stamp
```

This comment about the Makefile still applies: https://github.com/spruceid/didkit/pull/17#discussion_r550337800

The license field in `native/Cargo.toml` should probably be changed to match the rest of the repo.

**Comment by theosirian** [comment]
Building correctly for me as well. I have made the changes you requested.

**Comment by clehner** [comment]
Great. After #55's CI run completes, I will merge #55. Then this PR can be rebased/squashed onto `main` to see if the CI works and then merge.

**Comment by clehner** [comment]
#55 is merged; can you rebase and squash this PR?

**Comment by clehner** [comment]
Build failed because it adds features rsa, rand, etc. while ring is enabled in the same invocation, which I didn't notice before. This could be addressed by splitting the build invocation and adding `didkit_node` to `--exclude` like in <https://github.com/spruceid/didkit/pull/52#issuecomment-774223497>. Alternatively, the node package could be changed to use ssi's default features (ring), as follows. Doing so builds and works on my machine. Is there a reason to prefer the non-ring dependencies for the node package?

```diff
diff --git a/lib/node/native/Cargo.toml b/lib/node/native/Cargo.toml
index 471c018..8023800 100644
--- a/lib/node/native/Cargo.toml
+++ b/lib/node/native/Cargo.toml
@@ -16,3 +16,3 @@ neon-build = "0.6.0"
 [dependencies]
-ssi = { path = "../../../../ssi", default-features = false, features = ["ed25519-dalek", "sha2", "rsa", "rand"] }
+ssi = { path = "../../../../ssi"  }
 didkit = { path = "../../", default-features = false }
```

**Comment by theosirian** [comment]
No reason at all, I guess I blindly copied it from the WASM setup when updating the API. I've changed that and rebased to current `main`.

**Comment by clehner** [comment]
Thanks, @theosirian

**Pull request merged**
