### PR TITLE
Renames functions in Python package to follow snake case convention

### PR DESCRIPTION
**Pull request by theosirian**
Changes the names of the functions and parameters used to follow python conventions of snake case.

### CODE REVIEW

**Comment by clehner** [comment]
Would it be useful to make this a non-breaking change, so that the python package version could stay more in sync with the didkit crate version? The old functions could be kept but marked as deprecated, and removed in the next semver-major version (0.3.0).

**Comment by w4ll3** [comment]
> Would it be useful to make this a non-breaking change, so that the python package version could stay more in sync with the didkit crate version? The old functions could be kept but marked as deprecated, and removed in the next semver-major version (0.3.0).

I agree with that, if I'm not mistaken Adrian was already using it

**Comment by agropper** [comment]
Don’t worry about HIE of One. There’s no forks or users of the code that I
know of and Spruce can recompile the demo anytime you choose.

- Adrian

**Comment by theosirian** [comment]
I've added the deprecation warning using [`deprecated`](https://pypi.org/project/Deprecated/).

**Comment by clehner** [comment]
@theosirian thanks, looks good.
There is a build error now though, related to the version change.

**Comment by theosirian** [comment]
The install command on the `Makefile` looks for a version of the python package based on the `cargo` crate version, should we replace that with a similar `grep` from `setup.cfg` or maybe even just hardcode it?

**Comment by clehner** [comment]
Getting the version of the Python package from `setup.cfg` would make more sense I think. Hard-coding is an option, just another place to update during releases. But the command is already using a wildcard; would it be simpler it omit the version string there?
```diff
diff --git a/lib/Makefile b/lib/Makefile
index 9d34fde..fd1b6e4 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -61 +61 @@ install-python: $(TARGET)/test/python.stamp
-	python3 -m pip install python/dist/didkit-$(VERSION)-*.whl
+	python3 -m pip install python/dist/didkit-*.whl
```

**Comment by theosirian** [comment]
Yeah, that also works, I'll do it that way.

**Pull request merged**
