### PR TITLE
did:ion and DID operations

### PR DESCRIPTION
**Pull request by clehner**
Integrate Sidetree/ION implementation and DID operations from https://github.com/spruceid/ssi/pull/379.

- [x] Add did:ion method/resolver
- [x] Add generate-secp256k1-key command
- [x] Add create command
- [x] Submit operations to Sidetree/ION API
- [x] Add update command
- [x] Add recover command
- [x] Add deactivate command
- [x] Update readme to document new commands

## Example Usage
```
# Generate initial keys
$ didkit generate-secp256k1-key > update0.jwk
$ didkit generate-secp256k1-key > recovery0.jwk
$ didkit generate-secp256k1-key > signing0.jwk

# Create DID
$ did=$(didkit did-create ion -r recovery0.jwk -u update0.jwk -s signing0.jwk)

# Resolve long-form DID
$ DID_ION_API_URL=http://localhost:3000/ didkit did-resolve "$did"
```

### CODE REVIEW

**Comment by sbihel** [comment]
Do you think you will move to subcommands before merging?

**Comment by clehner** [comment]
@sbihel I don't think so, unless there is a straightforward way to do it

**Comment by clehner** [comment]
Opened #266 about the CLI

**Review by sbihel — APPROVED** [review]

**Comment by clehner** [comment]
Rebased and merged.
Docker image publish failed because ssi@main updated to v0.4 while didkit is not yet ready for ssi v0.4: https://github.com/spruceid/didkit/runs/5398417705?check_suite_focus=true
https://github.com/spruceid/ssi/pull/401 should have been merged after this PR for that workflow to have succeeded. This will be fixed when didkit is updated to use ssi v0.4.

**Pull request merged**
