### PR TITLE
Update Changelog with changes since v0.1.0

### PR DESCRIPTION
**Pull request by clehner**
Prepare for `v0.2.0` release: #119 

See also: `ssi` Changelog updates https://github.com/spruceid/ssi/pull/143

### CODE REVIEW

**Review by sbihel — APPROVED** [review]
Maybe specify did:tz layers 2 & 3. And for WASM maybe say that enabling HTTP brings the features to parity with the other platforms?

**Comment by clehner** [comment]
> did:tz layers 2 & 3

I think this would be covered by the `ssi` changelog:
https://github.com/spruceid/ssi/commit/1ecb3d90a0fdd06a4ae3b34064a908918b51a230#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR30
Or were there changes in `didkit` specifically for this?

I've added a link now to `ssi`'s changes, including its updated changelog. When we have a tagged release we could link to that instead of the GitHub compare changes page. Also updated the `ssi` CI ref to match.

> enabling HTTP brings the features to parity with the other platforms?

Updated.

Changes rebased onto latest `main`.

**Comment by sbihel** [comment]
> Or were there changes in didkit specifically for this?

No, I was just thinking in case someone is lazy and only looking at the changelog for DIDKit they might miss some things, but the link to the `ssi` changelog is more elegant :+1:

**Review by wyc — APPROVED** [review]

**Comment by clehner** [comment]
Updated since #125 #115 #117 were merged

**Comment by clehner** [comment]
Rebased

**Pull request merged**
