### PR TITLE
Add scheduled smoke test to install stable didkit

### LINKED ISSUE #197: Setup new CI/CD workflow to test `cargo install` comprehensively
To prevent https://github.com/spruceid/didkit/issues/196 from recurring.

### PR DESCRIPTION
**Pull request by sbihel**
Close #197

### CODE REVIEW

**Comment by sbihel** [comment]
@clehner is our Matrix server publicly addressable again?

**Comment by clehner** [comment]
>  is our Matrix server publicly addressable again?

Yes, but does not have federation.

**Review by clehner — APPROVED** [review]
Should also install `didkit-http`?

**Comment by sbihel** [comment]
> Should also install `didkit-http`?

I was thinking that the CLI partially covers the HTTP server, and that the most common way to install it is with Docker? But I can add it if you think it would be valuable.

**Pull request merged**
