### PR TITLE
Flutter Library Updates

### PR DESCRIPTION
**Pull request by theosirian**
I was updating dependencies on Credible in preparation for the upcoming Dart [nullsafety](https://dart.dev/null-safety/migration-guide) and ended up having to also update the `ffi` version on the library to match. I took the liberty to also add the same lint options I'm using on Credible, update .gitignore, and remove the default example.

### CODE REVIEW

**Comment by theosirian** [comment]
[Seems like it was a bad idea to remove the `example`.](https://github.com/flutter/flutter/issues/66561)

**Comment by clehner** [comment]
@theosirian looks good. Plugin builds and tests pass.

How/when/where is the linter run? I tried changing some of the double-quotes back to single-quotes to trigger it but `flutter pub get` and `flutter test` still complete without error or warning.

**Comment by theosirian** [comment]
Sorry, it's `flutter analyze`. I haven't included it in the workflow. And after restoring the example, it probably won't pass because of it.

**Comment by clehner** [comment]
Ok, got it.

**Comment by clehner** [comment]
I opened a new issue about removing the example plugin: https://github.com/flutter/flutter/issues/75644

However now I am thinking maybe it would be useful to keep the example plugin and make it work. It could be useful for developing and testing platform-dependent features in DIDKit, as part of a quicker develop-run cycle than with using Credible.

**Pull request merged**
